version: "3.8"

services:
  web:
    image: ghcr.io/kotulskim/swarm-demo:latest
    ports:
      - "88:5005"
    environment:
      APP_ENV: PROD
      APP_VERSION: "1.0"
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
