version: "3.8"

services:
  web:
    image: ghcr.io/kotulskim/swarm-demo:${APP_TAG}
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    networks:
      - traefik-public
      - backend
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == app
        preferences:
          - spread: node.id
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swarmdemo.rule=Host(`app.local`)"
        - "traefik.http.routers.swarmdemo.entrypoints=web"
        - "traefik.http.routers.swarmdemo.service=swarmdemo-svc"
        - "traefik.http.services.swarmdemo-svc.loadbalancer.server.port=5005"
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: any

  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend


  redis:
    image: redis:7-alpine
  
    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis_data:/data

    networks:
      - backend

    deploy:
      replicas: 1

      placement:
        constraints:
          - node.labels.role == infra

volumes:
  pgdata:
  redis_data:

secrets:
  db_password:
    external: true

networks:
  traefik-public:
    external: true
  backend:
