version: "3.8"

services:
  web:
    image: ghcr.io/kotulskim/swarm-demo:latest
    ports:
      - "88:5005"
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    deploy:
      replicas: 2

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

secrets:
  db_password:
    external: true
